# ===
# DELETE http://localhost:5000/users/2


# ===
# PATCH http://localhost:5000/users/1
# Content-Type: application/json

# {
#     "name": "Renaldi",
#     "email": "renaldi@gmail.com",
#     "gender": "Male"
# }

# ===
# POST http://localhost:5000/users
# Content-Type: application/json

# {
#     "name": "John Do",
#     "email": "john@gmail.com",
#     "gender": "Male"
# }


# ===
# GET h/ttp://localhost:5000/users/1


# ===
GET http://localhost:5000/users